= All you ever wanted to know about Usenet
:toc:

<<<

== Forward from the year 2020

What year is it?

== Introduction

This list of Usenet Files was compiled in order that you can get the
best out of Usenet while at the same time following the basic Network
Rules.  Many a times there have been complaints from the Usenet Community
about the new users not following the proper Nettiquette or are unaware of
the documentation available on the subject.  This is an attempt to
demystify Usenet.  More installments and updates will follow.

In the previous releases, I tried to keep the contents of this ZIP simple
but believe that it wouldn't hurt to add some documents of a more technical
nature.  RFC822 and RFC1153 attempt to show some more technical aspects of
Usenet.

I also upload the latest Canadian and World UUCP maps to CRS.  Look for
UCAN0791.ZIP and UMAP9107.ZIP.  These are July 91 Canadian and World Usenet
maps.

You can find me on Canada Remote Systems in Toronto, in Usenet
Conference 8, where I am one of the Conference Coordinators.  If you have
any further questions contact me at one of the following email addresses:

jzl@micasa.guild.org
jack.lupic@canrem.uucp

Jack Lupic
Scarborough
Ontario, Canada
Sat  07-27-1991  18:03 EDT


NOTICE: These compilations are the property of Jack Lupic and are copyrighted.
They may be used for personal purposes only.  They may not be incorporated in
other disk listings, nor altered  in any manner.  This notice must remain a
part of any use of these listings.

Previous Editions:

1. USENET1.ZIP     August 1990
2. USENET2.ZIP     February 1991
3. USNT9105.ZIP    May 1991

== Introduction to news.announce
include::A[]
<<<

== Rules for posting to Usenet
include::B[]
<<<

== Answers to Frequently Asked Questions
include::C[]
<<<

== A Primer on How to Work With the Usenet Community
include::D[]
<<<

== Emily Postnews Answers Your Questions on Netiquette
include::E[]
<<<

== Hints on writing style for Usenet
include::F[]
<<<

== How to Create a New Newsgroup
include::G[]
<<<

== USENET Software: History and Sources
include::H[]
<<<

== Alternative Newsgroup Hierarchies
include::I[]
<<<

== List of Active Newsgroups
include::J[]
<<<

== List of Moderators
include::K[]
<<<

== Publicly Accessible Mailing Lists
include::K[]
<<<

== How to Get Information about Networks
include::M[]
<<<

== List of Periodic Informational Postings
include::N[]
<<<

== Regional Newsgroup Hierarchies
include::O[]
<<<

== How to Create a Trial Newsgroup
include::P[]
<<<

== A Guide to Social Newsgroups and Mailing Lists
include::Q[]
<<<

== What is Usenet?
include::R[]
<<<

== How to Construct the Mailpaths File
include::S[]
<<<

== Brief Description on how to send Mail
include::ADDRESS[]
<<<

== How to Register Your Site in Usenet Maps <from rutgers.uucp>
include::README[]
<<<

== Standard for ARPA Internet Text Messages
include::RFC822[]
<<<

== UUCP Mail Interchange Format Standard
include::RFC0976[]
<<<

== Standard for Interchange of USENET Messages
include::RFC1036[]
<<<

== Choosing a Name for Your Computer
include::RFC1178[]
<<<

== The Smiley Dictionary
include::SMILEY[]
<<<

== Usenet Book Sources
include::USEBOOKS[]
<<<

== How to Use USENET Effectively, Supplement to files A - S
include::USENET.TXT[]
<<<
